from metaworld.policies import *

policies = {
    # ML 10
    'reach-v1': SawyerReachV2Policy,
    'push-v1': SawyerPushV2Policy,
    'pick-place-v1': SawyerPickPlaceV2Policy,
    'door-open-v1': SawyerDoorOpenV1Policy,
    'drawer-close-v1': SawyerDrawerCloseV1Policy,
    'button-press-topdown-v1': SawyerButtonPressTopdownV1Policy,
    'peg-insert-side-v1': SawyerPegInsertionSideV2Policy,
    'window-open-v1': SawyerWindowOpenV2Policy,
    'sweep-v1': SawyerSweepV1Policy,
    'basketball-v1': SawyerBasketballV1Policy,
    'drawer-open-v1': SawyerDrawerOpenV1Policy,
    'door-close-v1': SawyerDoorCloseV1Policy,
    'shelf-place-v1': SawyerShelfPlaceV1Policy,
    'sweep-into-v1': SawyerSweepIntoV1Policy,
    'lever-pull-v1': SawyerLeverPullV2Policy,
}
# others, needs review
"""
'window-close-v1': SawyerWindowCloseV2Policy,
'assembly-v1': SawyerAssemblyV1Policy,
'reach-wall-v1': SawyerReachWallV2Policy,
'pick-place-wall-v1': SawyerPickPlaceWallV2Policy,
'push-wall-v1': SawyerPushWallV2Policy,
'button-press-v1': SawyerButtonPressV1Policy,
'button-press-topdown-wall-v1': SawyerButtonPressTopdownWallV1Policy,
'button-press-wall-v1': SawyerButtonPressWallV1Policy,
'peg-unplug-side-v1': SawyerPegUnplugSideV1Policy,
'disassemble-v1': SawyerDisassembleV1Policy,
'hammer-v1': SawyerHammerV1Policy,
'plate-slide-v1': SawyerPlateSlideV1Policy,
'plate-slide-side-v1': SawyerPlateSlideSideV1Policy,
'plate-slide-back-v1': SawyerPlateSlideBackV1Policy,
'plate-slide-back-side-v1': SawyerPlateSlideBackSideV2Policy,
'handle-press-v1': SawyerHandlePressV1Policy,
'handle-pull-v1': SawyerHandlePullV1Policy,
'handle-press-side-v1': SawyerHandlePressSideV2Policy,
'handle-pull-side-v1': SawyerHandlePullSideV1Policy,
'stick-push-v1': SawyerStickPushV1Policy,
'stick-pull-v1': SawyerStickPullV1Policy,
'basketball-v1': SawyerBasketballV1Policy,
'soccer-v1': SawyerSoccerV1Policy,
'faucet-open-v1': SawyerFaucetOpenV1Policy,
'faucet-close-v1': SawyerFaucetCloseV1Policy,
'coffee-push-v1': SawyerCoffeePushV1Policy,
'coffee-pull-v1': SawyerCoffeePullV1Policy,
'coffee-button-v1': SawyerCoffeeButtonV1Policy,
'sweep-v1': SawyerSweepV1Policy,
'sweep-into-v1': SawyerSweepIntoV1Policy,
'pick-out-of-hole-v1': SawyerPickOutOfHoleV1Policy,
'shelf-place-v1': SawyerShelfPlaceV1Policy,
'push-back-v1': SawyerPushBackV1Policy,
'lever-pull-v1': SawyerLeverPullV2Policy,
'dial-turn-v1': SawyerDialTurnV1Policy,
'bin-picking-v1': SawyerBinPickingV2Policy,
'box-close-v1': SawyerBoxCloseV1Policy,
'hand-insert-v1': SawyerHandInsertV1Policy,
'door-lock-v1': SawyerDoorLockV1Policy,
'door-unlock-v1': SawyerDoorUnlockV1Policy,
"""

